import type { Metadata } from "next";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Navbar from "@/components/Navbar";
import Providers from "@/lib/providers";
import ClientInitializer from "@/components/ClientInitializer";

export const metadata: Metadata = {
  title: "Blog Next-Hono-Drizzle",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="full antialiased" suppressHydrationWarning>
      <head>
        <script
          suppressHydrationWarning
          dangerouslySetInnerHTML={{
            __html: `(function() {
              try {
                var theme = localStorage.getItem('theme') || 'forest';
                document.documentElement.setAttribute('data-theme', theme);
              } catch(e) {}
            })();`,
          }}
        />
      </head>
      <body className="min-h-screen flex flex-col">
        <ClerkProvider>
          <Providers>
            <ClientInitializer>
              <Navbar />
              <main className="grow w-full max-w-full mx-auto px-4 sm:px-6 lg:px-8">
                {children}
              </main>
            </ClientInitializer>
          </Providers>
        </ClerkProvider>
      </body>
    </html>
  );
}
